---
default:
  tags:
    - crab3

stages:
  - trigger

pull_and_push:
  rules:
    - if: $GITHUB_REF
  variables:
    GIT_STRATEGY: none
  stage: trigger
  image:
    name: registry.cern.ch/cmscrab/buildtools
    entrypoint: [""]
  script:
    - git clone https://github.com/novicecpp/CRABServer --branch ${GITHUB_REF} --single-branch CRABServer
    - cd CRABServer
    - git remote add origin https://${GITLAB_ACCESS_TOKEN_NAME}:${GITLAB_ACCESS_TOKEN}@gitlab..cern.ch/tseethon/crabserver.git
    - git push origin ${GITHUB_REF}
