---
default:
  tags:
    - tseethon
stages:
  #- build_docker
  - deploy

#build_rest_image:
#  stage: build_docker
#  image:
#    name: gcr.io/kaniko-project/executor:v1.14.0-debug
#    entrypoint: [""]
#  script:
#    - echo "{\"auths\":{\"$CMSCRAB_REGISTRY_URL\":{\"auth\":\"$(echo -n $CMSCRAB_REGISTRY_USER:$CMSCRAB_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
#    - cat /kaniko/.docker/config.json
#    - /kaniko/executor
#      --context "${CI_PROJECT_DIR}"
#      --dockerfile "${CI_PROJECT_DIR}/cicd/crabserver_pypi/Dockerfile"
#      --destination "registry.cern.ch/cmscrab/crabserver:pypi-${CI_COMMIT_SHA}"
#
#build_tw_image:
#  stage: build_docker
#  image:
#    name: gcr.io/kaniko-project/executor:v1.14.0-debug
#    entrypoint: [""]
#  script:
#    - echo "{\"auths\":{\"$CMSCRAB_REGISTRY_URL\":{\"auth\":\"$(echo -n $CMSCRAB_REGISTRY_USER:$CMSCRAB_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
#    - cat /kaniko/.docker/config.json
#    - /kaniko/executor
#      --context "${CI_PROJECT_DIR}"
#      --dockerfile "${CI_PROJECT_DIR}/cicd/crabtaskworker_pypi/Dockerfile"
#      --destination "registry.cern.ch/cmscrab/crabserver:pypi-${CI_COMMIT_SHA}"

deploy_server:
  stage: deploy
  image:
    name: docker.io/bitnami/kubectl:1.27
    entrypoint: [""]
  script:
    - echo $KUBECONFIG_FILE
    #- export KUBECONFIG=$KUBECONFIG_FILE
    #- kubectl -n crab set image deployment/crabserver "crabserver=registry.cern.ch/cmscrab/crabtaskworker:pypi-${CI_COMMIT_SHA}"


deploy_tw:
  stage: deploy
  image:
    name: registry.cern.ch/cmscrab/buildtools:latest
    #entrypoint: ["/bin/bash", "-x", "-l", "-c"]
  script:
    - echo "${CRAB_TW_SSH_KEY}"
#    - export Environment=crab-dev-tw03
#    - export Service=TaskWorker
#    - export Image="registry.cern.ch/cmscrab/crabtaskworker:pypi-${CI_COMMIT_SHA}"
#    - export SSH_KEY=$CRAB_TW_SSH_KEY
#    - bash -x cicd/jenkins/deploy_tw.sh
