# make runtime
FROM python:3.8 as bin-build
RUN install -d -m '0755' -o 1000 -g 1000 /build \
    && apt-get update \
    && apt-get install -y curl zip \
    && apt-get clean all
USER 1000:1000
WORKDIR /build
COPY htcondor_make_runtime.sh /build
ENV CRAB3_VERSION=v3.230921
SHELL ["/bin/bash", "-c"]
RUN curl -Lo WMCore.zip https://github.com/dmwm/WMCore/archive/refs/tags/2.1.8.zip \
    && curl -Lo CRABServer.zip https://github.com/dmwm/CRABServer/archive/refs/tags/v3.230921.zip \
    && unzip WMCore.zip \
    && unzip CRABServer.zip \
    && mv CRABServer-3.230921 CRABServer \
    && mv WMCore-2.1.8 WMCore
RUN bash htcondor_make_runtime.sh
RUN install -d /build/install_dir \
    && pushd CRABServer \
    && python3 setup.py install_system -s TaskWorker --prefix=/build/install_dir \
    && popd \
    && cp /build/CMSRunAnalysis-${CRAB3_VERSION}.tar.gz /build/install_dir/data/CMSRunAnalysis.tar.gz \
    && cp /build/TaskManagerRun-${CRAB3_VERSION}.tar.gz /build/install_dir/data/TaskManagerRun.tar.gz \
